# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person_married'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(max_length=30, null=True, verbose_name=b'profession'),
        ),
    ]
